/* Component classes. Each is a generated, scoped class name (zero runtime).
 * Imported as a single `classes` object by the HTML views.
 */

import { globalStyle, style } from "@vanilla-extract/css";
import { vars } from "./theme.css";

// The rendered README on a repo's summary tab. Its markup is generated by
// src/markdown.ts as bare elements, so the rules for those live in globalStyle
// scoped under this class (see the block below the class map).
const readme = style({
  margin: "1rem 0",
  padding: "1rem 1.25rem",
  background: vars.surface,
  border: `1px solid ${vars.border}`,
  borderRadius: vars.radius,
  overflowWrap: "break-word",
});

export const classes = {
  readme,

  siteHeader: style({
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0.75rem 1.25rem",
    borderBottom: `1px solid ${vars.border}`,
    background: vars.bgRaised,
  }),

  siteTitle: style({
    fontWeight: 700,
    fontSize: "1.1rem",
    color: vars.text,
  }),

  siteNav: style({
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
  }),

  navLink: style({ color: vars.accent }),

  user: style({ color: vars.textMuted }),

  content: style({
    maxWidth: "960px",
    margin: "0 auto",
    padding: "1.25rem",
  }),

  pageTitle: style({
    fontSize: "1.4rem",
    margin: "0.25rem 0 1rem",
  }),

  sectionTitle: style({
    fontSize: "1.05rem",
    margin: "1.5rem 0 0.5rem",
    color: vars.textSoft,
  }),

  repoList: style({}),

  repoRow: style({}),

  repoName: style({ fontWeight: 600 }),

  repoDesc: style({ color: vars.textMuted }),

  repoVis: style({
    fontFamily: vars.mono,
    fontSize: "0.85em",
    color: vars.textDim,
  }),

  repoIdle: style({
    fontFamily: vars.mono,
    fontSize: "0.85em",
    color: vars.textDim,
    whiteSpace: "nowrap",
  }),

  repoTabs: style({
    display: "flex",
    gap: "0.5rem",
    margin: "0.75rem 0",
  }),

  tab: style({
    padding: "0.2rem 0.7rem",
    border: `1px solid ${vars.border}`,
    borderRadius: vars.radius,
    color: vars.textSoft,
  }),

  tabActive: style({
    background: vars.surfaceHi,
    color: vars.text,
    fontWeight: 600,
  }),

  cloneBox: style({
    margin: "1rem 0",
    padding: "0.6rem 0.9rem",
    background: vars.surface,
    border: `1px solid ${vars.border}`,
    borderRadius: vars.radius,
  }),

  cloneLabel: style({
    color: vars.textMuted,
    marginRight: "0.5rem",
  }),

  commitList: style({}),

  commitDate: style({
    fontFamily: vars.mono,
    fontSize: "0.85em",
    color: vars.textDim,
    whiteSpace: "nowrap",
  }),

  commitSubject: style({}),

  commitAuthor: style({ color: vars.textMuted }),

  commitHash: style({
    fontFamily: vars.mono,
    fontSize: "0.85em",
    color: vars.textDim,
  }),

  treeList: style({}),

  treeMode: style({
    fontFamily: vars.mono,
    fontSize: "0.85em",
    color: vars.textDim,
  }),

  treeName: style({}),

  treeSize: style({
    fontFamily: vars.mono,
    fontSize: "0.85em",
    color: vars.textDim,
    textAlign: "right",
  }),

  code: style({
    display: "block",
    padding: "0.75rem 1rem",
    background: vars.surface,
    border: `1px solid ${vars.border}`,
    borderRadius: vars.radius,
    fontSize: "0.85rem",
    color: vars.textSoft,
  }),

  commitMeta: style({
    display: "grid",
    gridTemplateColumns: "max-content 1fr",
    gap: "0.2rem 1rem",
    margin: "0.75rem 0",
  }),

  binaryNotice: style({ color: vars.textMuted }),

  message: style({ color: vars.textMuted }),

  empty: style({ color: vars.textDim }),

  siteFooter: style({
    color: vars.textDim,
    textAlign: "center",
    padding: "2rem 0",
    fontSize: "0.85em",
  }),
} as const;

// ---- rendered README --------------------------------------------------------
// Element rules for markdown output. Scoped under .readme so they can't leak
// into the rest of the viewer, which styles by class.

globalStyle(`${readme} > :first-child`, { marginTop: 0 });
globalStyle(`${readme} > :last-child`, { marginBottom: 0 });

globalStyle(
  `${readme} h1, ${readme} h2, ${readme} h3, ${readme} h4, ${readme} h5, ${readme} h6`,
  {
    fontWeight: 600,
    lineHeight: 1.25,
    margin: "1.5rem 0 0.75rem",
  },
);

globalStyle(`${readme} h1`, { fontSize: "1.5rem" });
globalStyle(`${readme} h2`, { fontSize: "1.25rem" });
globalStyle(`${readme} h3`, { fontSize: "1.05rem" });
globalStyle(`${readme} h4, ${readme} h5, ${readme} h6`, {
  fontSize: "0.95rem",
  color: vars.textSoft,
});

globalStyle(`${readme} h1, ${readme} h2`, {
  paddingBottom: "0.3rem",
  borderBottom: `1px solid ${vars.border}`,
});

globalStyle(`${readme} p`, { margin: "0.75rem 0" });

globalStyle(`${readme} code`, {
  background: vars.surfaceHi,
  padding: "0.12em 0.35em",
  borderRadius: "4px",
  fontSize: "0.9em",
});

globalStyle(`${readme} pre`, {
  margin: "0.75rem 0",
  padding: "0.75rem 1rem",
  background: vars.bgDeep,
  border: `1px solid ${vars.border}`,
  borderRadius: vars.radius,
  overflowX: "auto",
});

globalStyle(`${readme} pre code`, {
  background: "none",
  padding: 0,
  borderRadius: 0,
  fontSize: "0.85rem",
  color: vars.textSoft,
});

globalStyle(`${readme} blockquote`, {
  margin: "0.75rem 0",
  padding: "0.1rem 0 0.1rem 1rem",
  borderLeft: `3px solid ${vars.border}`,
  color: vars.textMuted,
});

globalStyle(`${readme} ul, ${readme} ol`, {
  margin: "0.75rem 0",
  paddingLeft: "1.5rem",
});

globalStyle(`${readme} li`, { margin: "0.25rem 0" });

globalStyle(`${readme} li > input[type="checkbox"]`, {
  marginRight: "0.35rem",
});

globalStyle(`${readme} hr`, {
  border: 0,
  borderTop: `1px solid ${vars.border}`,
  margin: "1.5rem 0",
});

globalStyle(`${readme} img`, {
  maxWidth: "100%",
  verticalAlign: "middle",
});

// Wide tables scroll inside the README instead of stretching the page.
globalStyle(`${readme} table`, {
  display: "block",
  width: "max-content",
  maxWidth: "100%",
  overflowX: "auto",
  margin: "0.75rem 0",
});

globalStyle(`${readme} del`, { color: vars.textDim });

export type Classes = typeof classes;
